api_platform:
    title: Ecommerce API with API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    resource_class_directories:
        - '%kernel.project_dir%/src/Catalog/Domain/Model'
        - '%kernel.project_dir%/src/Shared/Domain/Model'
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
