security:
    password_hashers:
        App\User\Infrastructure\Security\SymfonyUserAdapter: 'auto'

    providers:
        app_user_provider:
            id: App\User\Infrastructure\Security\CustomUserProvider

    firewalls:
        #dev:
        #    pattern: ^/(_(profiler|wdt)|css|images|js)/
        #    security: false
        login:
            pattern: ^/api/login
            stateless: true
        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: '^/api(/?$|/(docs|contexts))', roles: PUBLIC_ACCESS }
        - { path: ^/api/users, methods: [POST], roles: PUBLIC_ACCESS }
        - { path: ^/api/products, methods: [GET], roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
