services:
  web:
    container_name: web
    build:
      dockerfile: ./.docker/Dockerfile
      target: nginx-local
      context: .
    volumes:
      - ./public:/var/www/html/public:ro
      - ./.docker/nginx/conf.d/local.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      default: ~
    ports:
      - 8088:80
  php:
    container_name: php
    user: 1000:1000
    build:
      dockerfile: .docker/Dockerfile
      target: php-dev
      context: .
    stop_signal: SIGTERM

    volumes:
      - ~/.composer:/var/www/.composer
      - .:/var/www/html
    depends_on:
      - db
    networks:
      default: ~
  db:
    image: mysql:${MYSQL_VERSION:-8.0}
    container_name: db
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-app}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-!ChangeMe!}
      - MYSQL_USER=${MYSQL_USER:-app}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-!ChangeMe!}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - database_data:/var/lib/mysql:rw
    networks:
      - default
    ports:
      - "3306:3306"
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
  database_data:
  rabbitmq_data:

networks:
  default:
    driver: bridge

