parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'

    App\Shared\Application\Bus\CommandBus:
        calls:
            - method: register
              arguments:
                  - App\User\Application\Command\LoginUserCommand
                  - '@App\User\Application\Handler\LoginUserHandler'
    App\Shared\Application\Bus\QueryBus:
        calls:
            - method: register
              arguments:
                  - App\User\Application\Query\GetLoggedUserQuery
                  - '@App\User\Application\Query\GetLoggedUserHandler'
