name: Run Tests in Docker

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
    test-in-docker:
        runs-on: ubuntu-latest

        steps:
            - name: Code download
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            # KROK 1: Obraz jest budowany tylko raz i tagowany.
            - name: Build and load Docker image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: ./.docker/Dockerfile
                  target: php-test
                  push: false
                  load: true
                  tags: ecommerce-api:ci-test

            - name: Running Static Analysis
              run: docker run --rm ecommerce-api:ci-test composer sa

            - name: Running Tests and Generating Reports
              run: |
                  docker run --name test-runner ecommerce-api:ci-test composer phpunit-ci

            - name: Copy reports from container
              if: always()
              run: |
                  if [ $(docker ps -a -q -f name=test-runner) ]; then
                    docker cp test-runner:/var/www/html/cobertura-coverage.xml .
                    docker cp test-runner:/var/www/html/junit-log.xml .
                    docker rm test-runner
                  fi

            - name: Upload coverage to Codecov
              if: success()
              uses: codecov/codecov-action@v4
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  file: ./cobertura-coverage.xml
                  fail_ci_if_error: true
